version: "3"

services:
  date:
    container_name: date-service
    build:
      context: ./services/date
    networks:
      - observability
    ports:
      - 3000:3000
    environment:
      DATE_SERVICE_HOSTNAME: date-service
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"

  gym:
    container_name: gym-service
    build:
      context: ./services/gym
    networks:
      - observability
    environment:
      DATE_SERVICE_HOSTNAME: date-service
      DATE_SERVICE_PORT: 3000
    ports:
      - 8000:8000
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        fluentd-async: "true"

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    networks:
      - observability
    ports:
      - 3100:3100
      - 7946:7946
      - 9095:9095
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

  fluent-bit:
    image: fluent/fluent-bit:2.2.0
    container_name: fluent-bit
    networks:
      - observability
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config/fluent-bit-parsers.conf:/fluent-bit/etc/fluent-bit-parsers.conf
    ports:
      - "24224:24224/tcp"
      - "24224:24224/udp"
    command: -c /fluent-bit/etc/fluent-bit.conf -log.level=debug

  grafana:
    image: grafana/grafana:10.2.1
    container_name: grafana
    networks:
      - observability
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3001:3000"
    volumes:
      - ./config/grafana.yaml:/etc/grafana/provisioning/datasources/ds.yaml
    entrypoint:
      - sh
      - -euc
      - /run.sh

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    networks:
      - observability
    ports:
      - 3200:3200
      - 4318:4318 # OTLP http receiver
    volumes:
      - ./config/tempo.yaml:/etc/tempo/config.yaml
    command: -config.file=/etc/tempo/config.yaml

networks:
  observability:
    name: observability
