version: "3"

services:
  date:
    container_name: date-service
    build:
      context: ./services/date
    networks:
      - observability
    ports:
      - 3000:3000

  gym:
    container_name: gym-service
    build:
      context: ./services/gym
    networks:
      - observability
    environment:
      DATE_SERVICE_HOSTNAME: date-service
      DATE_SERVICE_PORT: 3000
    ports:
      - 8000:8000

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    networks:
      - observability
    ports:
      - 3100:3100
      - 7946:7946
      - 9095:9095
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -print-config-stderr=true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1
      interval: 15s
      timeout: 5s
      retries: 5

networks:
  observability:
    name: observability
